-- TABLE
CREATE TABLE T_CATFACTS
(
  ID          NUMBER        NOT NULL,
  FACT        VARCHAR2(255) NOT NULL,
  LENGTH      NUMBER        NULL,

  CONSTRAINT T_CATFACTS_PK PRIMARY KEY (ID)
);

-- SEQUENCE
CREATE SEQUENCE  T_CATFACTS_SEQ START WITH 1 INCREMENT BY 100;

-- INSERT
INSERT into T_CATFACTS (ID, FACT, LENGTH) VALUES
(1, 'CATS GO MEOW', 12);